#! /bin/sh
# Get user 
user="${USER-$(id -u -n)}"

# Get host 
host="$(uname -n)"

# Get OS
. /etc/os-release # load lib
os="$PRETTY_NAME"

# Get kernel from uname
pkg="$(pacman -Qq | wc -l)"

# Shell
shell="${SHELL##*/}"

# Here you can write your wm
wm="i3"

# Colors and palette 
c0='[0m'
c1='[31m'; c2='[32m'
c3='[33m'; c4='[34m'
c5='[35m'; c6='[36m'
c7='[37m'; c8='[38m'

palette="[7m$c1 $c1 $c2 $c2 $c3 $c3 $c4 $c4 $c5 $c5 $c6 $c6 [m"

# Artwork from https://github.com/dylanaraps/pfetch
ARTR1="${c6}       /\\       "
ARTR2="${c6}      /  \\      "
ARTR3="${c6}     /\\   \\     "
ARTR4="${c4}    /      \\    "
ARTR5="${c4}   /   ,,   \\   "
ARTR6="${c4}  /   |  |  -\\  "
ARTR7="${c4} /_-''    ''-_\\ "

# Print
cat <<-EOF

    ${ARTR1}${user}${c0} in ${c2}${host}
    ${ARTR2}${c4}os${c0}      ${os}
    ${ARTR3}${c4}pkg${c0}     ${pkg}
    ${ARTR4}${c4}shell${c0}   ${shell}
    ${ARTR5}${c4}wm${c0}      ${wm}
    ${ARTR6}
    ${ARTR7}  ${palette}

EOF
