#! /bin/sh

# CatFetch, based on mfetch by depsterr: https://github.com/depsterr/mfetch

#####################
# Info
#####################

# Get user 
user="${USER-$(id -u -n)}"

# Get host 
host="$(uname -n)"

# Get OS
. /etc/os-release # load lib
os="$NAME"

# Packages (Pacman)
pkg="$(pacman -Qq | wc -l)"

# Shell
shell="${SHELL##*/}"

# Here you can write your wm or de
wm="i3"

#####################
# Colors and palette 
#####################

# Colors and palette method stolen from dylanaraps pftech: https://github.com/dylanaraps/pfetch
c0='[0m'
c1='[31m'; c2='[32m'
c3='[33m'; c4='[34m'
c5='[35m'; c6='[36m'
c7='[37m'; c8='[38m'
c9='^[[37m'

palette="[7m$c1 $c1 $c2 $c2 $c3 $c3 $c4 $c4 $c5 $c5 $c6 $c6 [m"

# Art based on https://www.asciiart.eu/animals/cats

ARTR1="${c0}  \    /\    "
ARTR2="${c0}   )  ( ')   "
ARTR3="${c0}  (  /  )    "
ARTR4="${c0}   \(__)|    "  

# Print
cat <<-EOF



 ${ARTR1}${c2}${user}${c0} in ${c4}${host}
 ${ARTR2}${c2}shell${c0}  ${shell}
 ${ARTR3}${c2}wm${c0}     ${wm}
 ${ARTR4}${c2}pkg${c0}    ${pkg}
        
             ${palette}


EOF
