#! /bin/sh

# FlowerFetch, based on mfetch by depsterr: https://github.com/depsterr/mfetch

# Get user 
user="${USER-$(id -u -n)}"

# Get host 
host="$(uname -n)"

# Get OS
. /etc/os-release # load lib
os="$NAME"

# Packages (Pacman)
pkg="$(pacman -Qq | wc -l)"

# Shell
shell="${SHELL##*/}"

# Here you can write your wm or de
wm="$(wmctrl -m | grep Name | cut -d: -f2)"

#####################
# Colors and palette 
#####################

# Colors and palette method stolen from dylanaraps pftech: https://github.com/dylanaraps/pfetch
c0='[0m'
c1='[31m'; c2='[32m'
c3='[33m'; c4='[34m'
c5='[35m'; c6='[36m'
c7='[37m'; c8='[38m'
c9='^[[37m'

palette="[7m$c1 $c1 $c2 $c2 $c3 $c3 $c4 $c4 $c5 $c5 $c6 $c6 [m"

# Art based on https://asciiart.website/index.php?art=plants/flowers

ARTR1="${c2}  |              "  #  _ _	 
ARTR2="${c2}  |__  o\        "  # (_\_)   
ARTR3="${c2}  | W    \O      "  #(__<__)  
ARTR4="${c2}  |       |\_    "  # (_/_)   
ARTR5="${c2}  |      /-\     "  #|\ |     
ARTR6="${c2}  |    /     \   "  # \\| /|  
ARTR7="${c2}  |              "  #  \|//   
ARTR8="${c2}  | Kobe ${c3}8 ${c2}| ${c5}24"  #   |/    

# Print
cat <<-EOF


  ${ARTR1}
  ${ARTR2}${c4}${user}${c0} in ${c6}${host}
  ${ARTR3}${c4}os${c0}     ${os}
  ${ARTR4}${c4}pkg${c0}    ${pkg}
  ${ARTR5}${c4}shell${c0}  ${shell}
  ${ARTR6}${c4}wm${c0}    ${wm}
  ${ARTR7}  
  ${ARTR8}  ${palette}

EOF
