#! /bin/sh
# Get user 
user="${USER-$(id -u -n)}"

# Get host 
host="$(uname -n)"

#Get Term
term="$(echo $TERM | grep -o -P '.*(?=-256color)')"

# Get OS
. /etc/os-release # load lib
os="$PRETTY_NAME"

# Get kernel from uname
pkg="$(pacman -Qq | wc -l)"

# Shell
shell="${SHELL##*/}"

# Here you can write your wm
wm="i3"

# Colors and palette 
c0='[0m'
c1='[31m'; c2='[32m'
c3='[33m'; c4='[34m'
c5='[35m'; c6='[36m'
c7='[37m'; c8='[38m'

palette="[7m$c1 $c1 $c2 $c2 $c3 $c3 $c4 $c4 $c5 $c5 $c6 $c6 [m"

ARTR1="${c1}     _ _	"	 
ARTR2="${c1}    (_\_)   "
ARTR3="${c1}   (__<__)  "
ARTR4="${c1}    (_/_)   "
ARTR5="${c2}   |\ |     "
ARTR6="${c2}    \\| /|  "
ARTR7="${c2}     \|//   "
ARTR8="${c2}      |/    "

# Print
cat <<-EOF


  ${ARTR1}
  ${ARTR2}${c4}${user}${c0} in ${c2}${host}
  ${ARTR3}${c4}os${c0}     ${os}
  ${ARTR4}${c4}pkg${c0}    ${pkg}
  ${ARTR5}${c4}shell${c0}  ${shell}
  ${ARTR6} ${c4}wm${c0}     ${wm}
  ${ARTR7}  
  ${ARTR8}  ${palette}

EOF
